### 好友申请
POST http://127.0.0.1:8881/v1/social/friend/putIn
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzk4Mzk5NjEsImlhdCI6MTc3MTE5OTk2MSwiemVyb0lNQ2hhdCI6IjB4MDAwMDAwODAwMDAwMDAwYyJ9.me7ZIQwxE44jWyHM7mEIjSsgEQshnR2YoWkGml1EpF4
Accept: application/json

{
  "req_msg": "通过一下",
  "user_uid": "0x000000800000000c"
}

### 处理好友申请
PUT http://127.0.0.1:8881/v1/social/friend/putIn
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzk4Mzk5NjEsImlhdCI6MTc3MTE5OTk2MSwiemVyb0lNQ2hhdCI6IjB4MDAwMDAwODAwMDAwMDAwYyJ9.me7ZIQwxE44jWyHM7mEIjSsgEQshnR2YoWkGml1EpF4
Accept: application/json

{
  "friend_req_id": 5,
  "handle_result": 4
}

### 好友列表
GET http://127.0.0.1:8881/v1/social/friends
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzk4Mzk5NjEsImlhdCI6MTc3MTE5OTk2MSwiemVyb0lNQ2hhdCI6IjB4MDAwMDAwODAwMDAwMDAwYyJ9.me7ZIQwxE44jWyHM7mEIjSsgEQshnR2YoWkGml1EpF4
Accept: application/json

{
}

### 好友申请列表
GET http://127.0.0.1:8881/v1/social/friend/putIns
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzk4Mzk5NjEsImlhdCI6MTc3MTE5OTk2MSwiemVyb0lNQ2hhdCI6IjB4MDAwMDAwODAwMDAwMDAwYyJ9.me7ZIQwxE44jWyHM7mEIjSsgEQshnR2YoWkGml1EpF4
Accept: application/json

{
}

### 创建群
POST http://127.0.0.1:8881/v1/social/group
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzk4Mzk5NjEsImlhdCI6MTc3MTE5OTk2MSwiemVyb0lNQ2hhdCI6IjB4MDAwMDAwODAwMDAwMDAwYyJ9.me7ZIQwxE44jWyHM7mEIjSsgEQshnR2YoWkGml1EpF4
Accept: application/json

{
  "name": "落云宗",
  "icon": "https://avatars.githubusercontent.com/u/32561714"
}

### 群列表
GET http://127.0.0.1:8881/v1/social/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzk4Mzk5NjEsImlhdCI6MTc3MTE5OTk2MSwiemVyb0lNQ2hhdCI6IjB4MDAwMDAwODAwMDAwMDAwYyJ9.me7ZIQwxE44jWyHM7mEIjSsgEQshnR2YoWkGml1EpF4
Accept: application/json

{
}

### 申请入群
POST http://127.0.0.1:8881/v1/social/group/putIn
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzk4NzMzNzMsImlhdCI6MTc3MTIzMzM3MywiemVyb0lNQ2hhdCI6IjB4MDAwMDAwODAwMDAwMDAwNCJ9.CojVexV88pN6dx6h_L7dDpnn4rR81F3nBLbSukUgnMY
Accept: application/json

{
  "group_id": "0x0000009000000001",
  "join_source": 2,
  "req_msg": "不请自来"
}