### 登录
POST http://127.0.0.1:8888/v1/user/login
Content-Type: application/json

{
  "phone": "13512341234",
  "password": "123456"
}

> {%
    // 响应处理脚本（适用于 JetBrains HTTP Client）
    client.global.set("auth_token", response.body.data.token);
%}

### 注册
POST http://127.0.0.1:8888/v1/user/register
Content-Type: application/json

{
  "phone": "13512341234",
  "password": "123456",
  "nickname": "娜扎",
  "sex": 1,
  "avatar": "https://avatars.githubusercontent.com/u/30550573"
}

### 获取登录用户信息
GET http://127.0.0.1:8888/v1/user/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzkzNzM4MDksImlhdCI6MTc3MDczMzgwOSwiemVyb0lNQ2hhdCI6IjB4MDAwMDAwNjAwMDAwMDAwMSJ9.JmT4wn3cP7YIbkUyfdx1xFUZa1Lp_NlxNJprgmynaUg
Accept: application/json

{
}