### 登录
POST http://127.0.0.1:8888/v1/user/login
Content-Type: application/json

{
  "phone": "13512341234",
  "password": "123456"
}

### 注册
POST http://127.0.0.1:8888/v1/user/register
Content-Type: application/json

{
  "phone": "13512341234",
  "password": "123456",
  "nickname": "娜扎",
  "sex": 1,
  "avatar": "https://avatars.githubusercontent.com/u/30550573"
}

### 获取登录用户信息
GET http://127.0.0.1:8888/v1/user/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzE1NTE2NTYsImlhdCI6MTc3MTQ2NTI1NiwiemVyb0lNQ2hhdCI6IjB4MDAwMDAwODAwMDAwMDAwYyJ9.SxFsAA5lzNi23-r9pL3SOXlWaVIyafg5quH28fYBXJQ
Accept: application/json

{
}