// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"zeroIM/apps/social/models"
)

func newGroupRequest(db *gorm.DB, opts ...gen.DOOption) groupRequest {
	_groupRequest := groupRequest{}

	_groupRequest.groupRequestDo.UseDB(db, opts...)
	_groupRequest.groupRequestDo.UseModel(&models.GroupRequest{})

	tableName := _groupRequest.groupRequestDo.TableName()
	_groupRequest.ALL = field.NewAsterisk(tableName)
	_groupRequest.ID = field.NewInt64(tableName, "id")
	_groupRequest.ReqID = field.NewString(tableName, "req_id")
	_groupRequest.GroupID = field.NewString(tableName, "group_id")
	_groupRequest.ReqMsg = field.NewString(tableName, "req_msg")
	_groupRequest.ReqTime = field.NewTime(tableName, "req_time")
	_groupRequest.JoinSource = field.NewInt64(tableName, "join_source")
	_groupRequest.InviterUserID = field.NewString(tableName, "inviter_user_id")
	_groupRequest.HandleUserID = field.NewString(tableName, "handle_user_id")
	_groupRequest.HandleTime = field.NewTime(tableName, "handle_time")
	_groupRequest.HandleResult = field.NewInt64(tableName, "handle_result")
	_groupRequest.CreatedAt = field.NewTime(tableName, "created_at")
	_groupRequest.UpdatedAt = field.NewTime(tableName, "updated_at")
	_groupRequest.DeletedAt = field.NewField(tableName, "deleted_at")

	_groupRequest.fillFieldMap()

	return _groupRequest
}

type groupRequest struct {
	groupRequestDo groupRequestDo

	ALL           field.Asterisk
	ID            field.Int64
	ReqID         field.String // 请求id
	GroupID       field.String // 群id
	ReqMsg        field.String // 请求信息
	ReqTime       field.Time   // 请求时间
	JoinSource    field.Int64  // 入群方式
	InviterUserID field.String // 邀请人id
	HandleUserID  field.String // 处理人id
	HandleTime    field.Time   // 处理时间
	HandleResult  field.Int64  // 处理结果
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	DeletedAt     field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (g groupRequest) Table(newTableName string) *groupRequest {
	g.groupRequestDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g groupRequest) As(alias string) *groupRequest {
	g.groupRequestDo.DO = *(g.groupRequestDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *groupRequest) updateTableName(table string) *groupRequest {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.ReqID = field.NewString(table, "req_id")
	g.GroupID = field.NewString(table, "group_id")
	g.ReqMsg = field.NewString(table, "req_msg")
	g.ReqTime = field.NewTime(table, "req_time")
	g.JoinSource = field.NewInt64(table, "join_source")
	g.InviterUserID = field.NewString(table, "inviter_user_id")
	g.HandleUserID = field.NewString(table, "handle_user_id")
	g.HandleTime = field.NewTime(table, "handle_time")
	g.HandleResult = field.NewInt64(table, "handle_result")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")
	g.DeletedAt = field.NewField(table, "deleted_at")

	g.fillFieldMap()

	return g
}

func (g *groupRequest) WithContext(ctx context.Context) IGroupRequestDo {
	return g.groupRequestDo.WithContext(ctx)
}

func (g groupRequest) TableName() string { return g.groupRequestDo.TableName() }

func (g groupRequest) Alias() string { return g.groupRequestDo.Alias() }

func (g groupRequest) Columns(cols ...field.Expr) gen.Columns {
	return g.groupRequestDo.Columns(cols...)
}

func (g *groupRequest) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *groupRequest) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 13)
	g.fieldMap["id"] = g.ID
	g.fieldMap["req_id"] = g.ReqID
	g.fieldMap["group_id"] = g.GroupID
	g.fieldMap["req_msg"] = g.ReqMsg
	g.fieldMap["req_time"] = g.ReqTime
	g.fieldMap["join_source"] = g.JoinSource
	g.fieldMap["inviter_user_id"] = g.InviterUserID
	g.fieldMap["handle_user_id"] = g.HandleUserID
	g.fieldMap["handle_time"] = g.HandleTime
	g.fieldMap["handle_result"] = g.HandleResult
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
	g.fieldMap["deleted_at"] = g.DeletedAt
}

func (g groupRequest) clone(db *gorm.DB) groupRequest {
	g.groupRequestDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g groupRequest) replaceDB(db *gorm.DB) groupRequest {
	g.groupRequestDo.ReplaceDB(db)
	return g
}

type groupRequestDo struct{ gen.DO }

type IGroupRequestDo interface {
	gen.SubQuery
	Debug() IGroupRequestDo
	WithContext(ctx context.Context) IGroupRequestDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGroupRequestDo
	WriteDB() IGroupRequestDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGroupRequestDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGroupRequestDo
	Not(conds ...gen.Condition) IGroupRequestDo
	Or(conds ...gen.Condition) IGroupRequestDo
	Select(conds ...field.Expr) IGroupRequestDo
	Where(conds ...gen.Condition) IGroupRequestDo
	Order(conds ...field.Expr) IGroupRequestDo
	Distinct(cols ...field.Expr) IGroupRequestDo
	Omit(cols ...field.Expr) IGroupRequestDo
	Join(table schema.Tabler, on ...field.Expr) IGroupRequestDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGroupRequestDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGroupRequestDo
	Group(cols ...field.Expr) IGroupRequestDo
	Having(conds ...gen.Condition) IGroupRequestDo
	Limit(limit int) IGroupRequestDo
	Offset(offset int) IGroupRequestDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGroupRequestDo
	Unscoped() IGroupRequestDo
	Create(values ...*models.GroupRequest) error
	CreateInBatches(values []*models.GroupRequest, batchSize int) error
	Save(values ...*models.GroupRequest) error
	First() (*models.GroupRequest, error)
	Take() (*models.GroupRequest, error)
	Last() (*models.GroupRequest, error)
	Find() ([]*models.GroupRequest, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.GroupRequest, err error)
	FindInBatches(result *[]*models.GroupRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.GroupRequest) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGroupRequestDo
	Assign(attrs ...field.AssignExpr) IGroupRequestDo
	Joins(fields ...field.RelationField) IGroupRequestDo
	Preload(fields ...field.RelationField) IGroupRequestDo
	FirstOrInit() (*models.GroupRequest, error)
	FirstOrCreate() (*models.GroupRequest, error)
	FindByPage(offset int, limit int) (result []*models.GroupRequest, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGroupRequestDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g groupRequestDo) Debug() IGroupRequestDo {
	return g.withDO(g.DO.Debug())
}

func (g groupRequestDo) WithContext(ctx context.Context) IGroupRequestDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g groupRequestDo) ReadDB() IGroupRequestDo {
	return g.Clauses(dbresolver.Read)
}

func (g groupRequestDo) WriteDB() IGroupRequestDo {
	return g.Clauses(dbresolver.Write)
}

func (g groupRequestDo) Session(config *gorm.Session) IGroupRequestDo {
	return g.withDO(g.DO.Session(config))
}

func (g groupRequestDo) Clauses(conds ...clause.Expression) IGroupRequestDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g groupRequestDo) Returning(value interface{}, columns ...string) IGroupRequestDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g groupRequestDo) Not(conds ...gen.Condition) IGroupRequestDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g groupRequestDo) Or(conds ...gen.Condition) IGroupRequestDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g groupRequestDo) Select(conds ...field.Expr) IGroupRequestDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g groupRequestDo) Where(conds ...gen.Condition) IGroupRequestDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g groupRequestDo) Order(conds ...field.Expr) IGroupRequestDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g groupRequestDo) Distinct(cols ...field.Expr) IGroupRequestDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g groupRequestDo) Omit(cols ...field.Expr) IGroupRequestDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g groupRequestDo) Join(table schema.Tabler, on ...field.Expr) IGroupRequestDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g groupRequestDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGroupRequestDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g groupRequestDo) RightJoin(table schema.Tabler, on ...field.Expr) IGroupRequestDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g groupRequestDo) Group(cols ...field.Expr) IGroupRequestDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g groupRequestDo) Having(conds ...gen.Condition) IGroupRequestDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g groupRequestDo) Limit(limit int) IGroupRequestDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g groupRequestDo) Offset(offset int) IGroupRequestDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g groupRequestDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGroupRequestDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g groupRequestDo) Unscoped() IGroupRequestDo {
	return g.withDO(g.DO.Unscoped())
}

func (g groupRequestDo) Create(values ...*models.GroupRequest) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g groupRequestDo) CreateInBatches(values []*models.GroupRequest, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g groupRequestDo) Save(values ...*models.GroupRequest) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g groupRequestDo) First() (*models.GroupRequest, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.GroupRequest), nil
	}
}

func (g groupRequestDo) Take() (*models.GroupRequest, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.GroupRequest), nil
	}
}

func (g groupRequestDo) Last() (*models.GroupRequest, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.GroupRequest), nil
	}
}

func (g groupRequestDo) Find() ([]*models.GroupRequest, error) {
	result, err := g.DO.Find()
	return result.([]*models.GroupRequest), err
}

func (g groupRequestDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.GroupRequest, err error) {
	buf := make([]*models.GroupRequest, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g groupRequestDo) FindInBatches(result *[]*models.GroupRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g groupRequestDo) Attrs(attrs ...field.AssignExpr) IGroupRequestDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g groupRequestDo) Assign(attrs ...field.AssignExpr) IGroupRequestDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g groupRequestDo) Joins(fields ...field.RelationField) IGroupRequestDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g groupRequestDo) Preload(fields ...field.RelationField) IGroupRequestDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g groupRequestDo) FirstOrInit() (*models.GroupRequest, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.GroupRequest), nil
	}
}

func (g groupRequestDo) FirstOrCreate() (*models.GroupRequest, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.GroupRequest), nil
	}
}

func (g groupRequestDo) FindByPage(offset int, limit int) (result []*models.GroupRequest, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g groupRequestDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g groupRequestDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g groupRequestDo) Delete(models ...*models.GroupRequest) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *groupRequestDo) withDO(do gen.Dao) *groupRequestDo {
	g.DO = *do.(*gen.DO)
	return g
}
